# SAM Configuration File
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

version = 0.1

[default]
[default.global.parameters]
stack_name = "clkk-backend"

[default.build.parameters]
cached = true
parallel = true
use_container = false

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true

[default.sync.parameters]
watch = true

[dev]
[dev.global.parameters]
stack_name = "clkk-backend-dev"

[dev.deploy.parameters]
s3_prefix = "dev"
region = "us-east-1"
parameter_overrides = "Environment=dev"
confirm_changeset = false

[staging]
[staging.global.parameters]
stack_name = "clkk-backend-staging"

[staging.deploy.parameters]
s3_prefix = "staging"
region = "us-east-1"
parameter_overrides = "Environment=staging"
confirm_changeset = true

[prod]
[prod.global.parameters]
stack_name = "clkk-backend-prod"

[prod.deploy.parameters]
s3_prefix = "prod"
region = "us-east-1"
parameter_overrides = "Environment=prod"
confirm_changeset = true