AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Custom Domain Stack for CLKK Mobile Backend - Creates AppSync custom domain

Parameters:
  StackName:
    Type: String
    Description: Parent stack name
  
  Environment:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  # These come from SSM parameters set by platform stack
  RootDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /clkk/platform/domain-name
    Description: Root domain name from platform stack
  
  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /clkk/platform/hosted-zone-id
    Description: Route53 Hosted Zone ID from platform stack
  
  CertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /clkk/platform/certificates/mobile
    Description: SSL Certificate ARN for mobile subdomain
    
  GraphQLApiId:
    Type: String
    Description: AppSync GraphQL API ID

Conditions:
  IsProd: !Equals [!Ref Environment, prod]
  IsStaging: !Equals [!Ref Environment, staging]

Resources:
  # AppSync Custom Domain
  AppSyncCustomDomain:
    Type: AWS::AppSync::DomainName
    Properties:
      DomainName: !If
        - IsProd
        - !Sub "mobile-api.${RootDomain}"
        - !If
          - IsStaging
          - !Sub "mobile-api.staging.${RootDomain}"
          - !Sub "mobile-api.dev.${RootDomain}"
      CertificateArn: !Ref CertificateArn
      Description: !Sub "Custom domain for ${StackName} ${Environment} Mobile GraphQL API"

  # Associate the custom domain with the API
  DomainAssociation:
    Type: AWS::AppSync::DomainNameApiAssociation
    Properties:
      ApiId: !Ref GraphQLApiId
      DomainName: !Ref AppSyncCustomDomain

  # Cross-account DNS record (managed in prod account)
  DNSRecord:
    Type: Custom::CrossAccountDNS
    Properties:
      ServiceToken: !ImportValue 
        Fn::Sub: "${Environment}-cross-account-dns-function-arn"
      HostedZoneId: !Ref HostedZoneId
      RecordName: !If
        - IsProd
        - !Sub "mobile-api.${RootDomain}"
        - !If
          - IsStaging
          - !Sub "mobile-api.staging.${RootDomain}"
          - !Sub "mobile-api.dev.${RootDomain}"
      RecordType: A
      AliasTarget:
        DNSName: !GetAtt AppSyncCustomDomain.AppSyncDomainName
        HostedZoneId: !GetAtt AppSyncCustomDomain.HostedZoneId
        EvaluateTargetHealth: false

Outputs:
  CustomDomainName:
    Description: Custom domain name for the Mobile API
    Value: !If
      - IsProd
      - !Sub "mobile-api.${RootDomain}"
      - !If
        - IsStaging
        - !Sub "mobile-api.staging.${RootDomain}"
        - !Sub "mobile-api.dev.${RootDomain}"
    Export:
      Name: !Sub "${AWS::StackName}-domain-name"
  
  GraphQLEndpoint:
    Description: GraphQL endpoint URL via custom domain
    Value: !If
      - IsProd
      - !Sub "https://mobile-api.${RootDomain}/graphql"
      - !If
        - IsStaging
        - !Sub "https://mobile-api.staging.${RootDomain}/graphql"
        - !Sub "https://mobile-api.dev.${RootDomain}/graphql"
    Export:
      Name: !Sub "${AWS::StackName}-graphql-endpoint"
  
  AppSyncDomainName:
    Description: AppSync domain name (CloudFront distribution)
    Value: !GetAtt AppSyncCustomDomain.AppSyncDomainName
    Export:
      Name: !Sub "${AWS::StackName}-appsync-domain"
  
  AppSyncHostedZoneId:
    Description: AppSync hosted zone ID
    Value: !GetAtt AppSyncCustomDomain.HostedZoneId
    Export:
      Name: !Sub "${AWS::StackName}-appsync-zone-id"