AWSTemplateFormatVersion: "2010-09-09"
Description: Cross-Account DNS Management Role for Mobile Accounts (Deploy in PROD account)

Parameters:
  # Mobile accounts
  MobileDevAccountId:
    Type: String
    Default: "741448914938"
    Description: AWS Account ID of the mobile development account
    
  MobileStagingAccountId:
    Type: String
    Default: "REPLACE_WITH_STAGING_ACCOUNT_ID"
    Description: AWS Account ID of the mobile staging account
    
  MobileProdAccountId:
    Type: String
    Default: "REPLACE_WITH_PROD_ACCOUNT_ID"
    Description: AWS Account ID of the mobile production account

  # Existing CLKK accounts (optional, for backward compatibility)
  DevAccountId:
    Type: String
    Default: "734379247206"
    Description: AWS Account ID of the CLKK development account

  StagingAccountId:
    Type: String
    Default: "797098542572"
    Description: AWS Account ID of the CLKK staging account

  HostedZoneId:
    Type: String
    Default: "Z07794393NL0TD72QHLLD"
    Description: Route53 Hosted Zone ID

Resources:
  # Generic role that can be assumed by CloudFormation custom resources
  CrossAccountDNSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: clkk-cross-account-dns-role-mobile
      Description: Allows mobile dev/staging/prod accounts to manage DNS records in prod hosted zone
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                # Mobile accounts
                - !Sub "arn:aws:iam::${MobileDevAccountId}:root"
                - !If
                  - HasMobileStaging
                  - !Sub "arn:aws:iam::${MobileStagingAccountId}:root"
                  - !Ref AWS::NoValue
                - !If
                  - HasMobileProd
                  - !Sub "arn:aws:iam::${MobileProdAccountId}:root"
                  - !Ref AWS::NoValue
                # Existing CLKK accounts
                - !Sub "arn:aws:iam::${DevAccountId}:root"
                - !Sub "arn:aws:iam::${StagingAccountId}:root"
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId": "clkk-dns-management"
      Policies:
        - PolicyName: Route53DNSManagementPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:ListResourceRecordSets
                Resource:
                  - !Sub "arn:aws:route53:::hostedzone/${HostedZoneId}"
                  - "arn:aws:route53:::change/*"
              - Effect: Allow
                Action:
                  - route53:GetHostedZone
                Resource: !Sub "arn:aws:route53:::hostedzone/${HostedZoneId}"
      Tags:
        - Key: Purpose
          Value: Cross-account DNS management for mobile
        - Key: ManagedBy
          Value: CLKK Platform

Conditions:
  HasMobileStaging: !Not [!Equals [!Ref MobileStagingAccountId, "REPLACE_WITH_STAGING_ACCOUNT_ID"]]
  HasMobileProd: !Not [!Equals [!Ref MobileProdAccountId, "REPLACE_WITH_PROD_ACCOUNT_ID"]]

Outputs:
  CrossAccountRoleArn:
    Description: ARN of the cross-account DNS management role
    Value: !GetAtt CrossAccountDNSRole.Arn
    Export:
      Name: clkk-cross-account-dns-role-mobile-arn
      
  TrustPolicy:
    Description: Trust policy for this role
    Value: !Sub |
      Trusted accounts:
      - Mobile Dev: ${MobileDevAccountId}
      - Mobile Staging: ${MobileStagingAccountId}
      - Mobile Prod: ${MobileProdAccountId}
      - CLKK Dev: ${DevAccountId}
      - CLKK Staging: ${StagingAccountId}